apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins-k8s.fullname" . }}-agent
spec:
  type: {{ .Values.jnlp.service.type }}
  ports:
    - port: {{ .Values.jnlp.service.externalPort }}
      targetPort: {{ .Values.jnlp.service.internalPort }}
  selector:
    app: {{ template "jenkins-k8s.name" . }}
    release: {{ .Release.Name }}
