apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins-k8s.fullname" . }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.master.adminUser | b64enc | quote }}
  {{ if .Values.master.adminPassword -}}
  jenkins-admin-password: {{ .Values.master.adminPassword | b64enc | quote }}
  {{ else -}}
  jenkins-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}
  